name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Adjust based on your local Python version
    - name: Install dependencies
      run: |
        set -e  # Fail on any error
        python -m pip install --upgrade pip
        echo "Listing Python version and pip version for debugging:"
        python --version
        python -m pip --version
        echo "Installing scikit-learn:"
        python -m pip install scikit-learn==1.3.0
        python -c "import sklearn; print('scikit-learn version:', sklearn.__version__)"  # Verify scikit-learn is importable
        echo "Installing numpy:"
        python -m pip install numpy==1.24.3
        python -c "import numpy; print('numpy version:', numpy.__version__)"
        echo "Installing tensorflow:"
        python -m pip install tensorflow==2.15.0
        python -c "import tensorflow; print('tensorflow version:', tensorflow.__version__)"
        echo "Installing keras-tuner:"
        python -m pip install keras-tuner==1.3.5
        python -c "import keras_tuner; print('keras-tuner version:', keras_tuner.__version__)"
        echo "Installing matplotlib:"
        python -m pip install matplotlib==3.7.1
        python -c "import matplotlib; print('matplotlib version:', matplotlib.__version__)"
        echo "Installing pytest:"
        python -m pip install pytest==7.4.0
        python -c "import pytest; print('pytest version:', pytest.__version__)"
        echo "Listing installed packages for debugging:"
        python -m pip list
    - name: Set environment variables to suppress TensorFlow warnings
      run: |
        echo "CUDA_VISIBLE_DEVICES=" >> $GITHUB_ENV
        echo "TF_CPP_MIN_LOG_LEVEL=3" >> $GITHUB_ENV
    - name: Verify scikit-learn is importable
      run: |
        python -c "import sklearn; print('Successfully imported sklearn')"
    - name: Run tests
      run: |
        python -m pytest