name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      id: setup-python
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        set -e
        ${{ steps.setup-python.outputs.python-path }} -m pip install --upgrade pip
        echo "Listing Python version and pip version for debugging:"
        ${{ steps.setup-python.outputs.python-path }} --version
        ${{ steps.setup-python.outputs.python-path }} -m pip --version
        echo "Installing scikit-learn:"
        ${{ steps.setup-python.outputs.python-path }} -m pip install scikit-learn==1.2.2
        ${{ steps.setup-python.outputs.python-path }} -c "import sklearn; print('scikit-learn version:', sklearn.__version__)"
        echo "Installing numpy:"
        ${{ steps.setup-python.outputs.python-path }} -m pip install numpy==1.24.3
        ${{ steps.setup-python.outputs.python-path }} -c "import numpy; print('numpy version:', numpy.__version__)"
        echo "Installing tensorflow:"
        ${{ steps.setup-python.outputs.python-path }} -m pip install tensorflow==2.15.0
        ${{ steps.setup-python.outputs.python-path }} -c "import tensorflow; print('tensorflow version:', tensorflow.__version__)"
        echo "Installing keras-tuner:"
        ${{ steps.setup-python.outputs.python-path }} -m pip install keras-tuner==1.3.5
        ${{ steps.setup-python.outputs.python-path }} -c "import keras_tuner; print('keras-tuner version:', keras_tuner.__version__)"
        echo "Installing matplotlib:"
        ${{ steps.setup-python.outputs.python-path }} -m pip install matplotlib==3.7.1
        ${{ steps.setup-python.outputs.python-path }} -c "import matplotlib; print('matplotlib version:', matplotlib.__version__)"
        echo "Installing pytest:"
        ${{ steps.setup-python.outputs.python-path }} -m pip install pytest==7.4.0
        ${{ steps.setup-python.outputs.python-path }} -c "import pytest; print('pytest version:', pytest.__version__)"
        echo "Listing installed packages for debugging:"
        ${{ steps.setup-python.outputs.python-path }} -m pip list
    - name: Set environment variables to suppress TensorFlow warnings
      run: |
        echo "CUDA_VISIBLE_DEVICES=" >> $GITHUB_ENV
        echo "TF_CPP_MIN_LOG_LEVEL=3" >> $GITHUB_ENV
    - name: Verify scikit-learn is importable
      run: |
        ${{ steps.setup-python.outputs.python-path }} -c "import sklearn; print('Successfully imported sklearn')"
    - name: Run tests
      run: |
        ${{ steps.setup-python.outputs.python-path }} -m pytest
    